
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2016-11-24T17:19:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "400e8e8dd006771f854a4c435b7f1f76e3371561",
 "version": "3.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
